headshot: /assets/img/mark_headshot_2026.png
show_downloads: false
google_analytics: G-FTK9XC05VE
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mark J. Escott
description: Product Owner, Software Analyst, Systems Analyst, Technical Business Analyst. Cybersecurity geek.
email: mark@cyberdarkdigital.com
website: https://www.linkedin.com/in/mjescott/
cspo_img: /assets/img/badge-7224.png
csa_img: /assets/img/servicenow-certified-system-administrator-csa.png
updated_date: May 27, 2026
