backend:
  name: github
  repo: mjescott/mjescott.github.io # Replace with your GitHub username and repository name
  branch: master # Replace with your default branch (main or master)
  site_domain: mjescott.github.io
  # If using an external OAuth provider, add these lines:
  base_url: https://auth.mescott.workers.dev
  auth_endpoint: /auth

media_folder: "assets/images/uploads" # Where images uploaded via the CMS will be saved
public_folder: "/assets/images/uploads" # The path Jekyll will use to serve the images

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    # Jekyll requires specific filename structures (YYYY-MM-DD-title.md)
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
